dat <- read.table("household_power_consumption.txt", header = TRUE, sep = ";")
datQ <- subset(dat, Date=="1/2/2007" | Date=="2/2/2007")
datQ$Sub_metering_1 <- as.numeric(as.character(datQ$Sub_metering_1))
datQ$Sub_metering_2 <- as.numeric(as.character(datQ$Sub_metering_2))
datQ$Sub_metering_3 <- as.numeric(as.character(datQ$Sub_metering_3))
datQ$DateTime <- as.POSIXct(paste(datQ$Date, datQ$Time), format="%d/%m/%Y %H:%M:%S")
png("plot3.png")
plot(datQ$DateTime, datQ$Sub_metering_1, type="l", col="black", ylab="Energy sub metering", xlab="")
lines(datQ$DateTime, datQ$Sub_metering_2, type="l", col="red", ylab="Energy sub metering", xlab="")
lines(datQ$DateTime, datQ$Sub_metering_3, type="l", col="blue", ylab="Energy sub metering", xlab="")
legend("topright", lty=1,col=c("black","red","blue"), legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()