dat <- read.table("household_power_consumption.txt", header = TRUE, sep = ";")
datQ <- subset(dat, Date=="1/2/2007" | Date=="2/2/2007")
datQ$Global_active_power <- as.numeric(as.character(datQ$Global_active_power))
datQ$DateTime <- as.POSIXct(paste(datQ$Date, datQ$Time), format="%d/%m/%Y %H:%M:%S")
png("plot2.png")
plot(datQ$DateTime, datQ$Global_active_power, type="l", ylab="Global Active Power(kilowatts)", xlab="")
dev.off()