dat <- read.table("household_power_consumption.txt", header = TRUE, sep = ";")
datQ <- subset(dat, Date=="1/2/2007" | Date=="2/2/2007")
datQ$Global_active_power <- as.numeric(as.character(datQ$Global_active_power))
png("plot1.png")
hist(datQ$Global_active_power, main="Global Active Power", col="red", xlab="Global Active Power")
dev.off()