dat <- read.table("household_power_consumption.txt", header = TRUE, sep = ";")
datQ <- subset(dat, Date=="1/2/2007" | Date=="2/2/2007")
datQ$DateTime <- as.POSIXct(paste(datQ$Date, datQ$Time), format="%d/%m/%Y %H:%M:%S")
datQ$Global_active_power <- as.numeric(as.character(datQ$Global_active_power))
datQ$Voltage <- as.numeric(as.character(datQ$Voltage))
datQ$Sub_metering_1 <- as.numeric(as.character(datQ$Sub_metering_1))
datQ$Sub_metering_2 <- as.numeric(as.character(datQ$Sub_metering_2))
datQ$Sub_metering_3 <- as.numeric(as.character(datQ$Sub_metering_3))
datQ$Global_reactive_power <- as.numeric(as.character(datQ$Global_reactive_power))
png("plot4.png")
par(mfrow = c(2,2), mar = c(4,4,2,1))
plot(datQ$DateTime, datQ$Global_active_power, type="l", ylab="Global Active Power(kilowatts)", xlab="")
plot(datQ$DateTime, datQ$Voltage, type="l", ylab="Voltage", xlab="datetime")
plot(datQ$DateTime, datQ$Sub_metering_1, type="l", col="black", ylab="Energy sub metering", xlab="")
lines(datQ$DateTime, datQ$Sub_metering_2, type="l", col="red", ylab="Energy sub metering", xlab="")
lines(datQ$DateTime, datQ$Sub_metering_3, type="l", col="blue", ylab="Energy sub metering", xlab="")
legend("topright", lty=1,col=c("black","red","blue"), legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), bty="n")
plot(datQ$DateTime, datQ$Global_reactive_power, type="l", ylab="Global_reactive_power", xlab="datetime")
dev.off()